apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/alkuzmanov/go/bin/kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: genesys
  name: genesys
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: genesys
status:
  loadBalancer: {}
