apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: /Users/alkuzmanov/go/bin/kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: genesyszipkin
  name: genesyszipkin
spec:
  containers:
    - env:
        - name: STORAGE_TYPE
          value: mem
      image: openzipkin/zipkin:2.22.2
      name: genesyszipkin
      ports:
        - containerPort: 9411
      resources: {}
  restartPolicy: OnFailure
status: {}
