apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/alkuzmanov/go/bin/kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: genesyszipkin
  name: genesyszipkin
spec:
  ports:
    - name: "9411"
      port: 9411
      targetPort: 9411
  selector:
    io.kompose.service: genesyszipkin
status:
  loadBalancer: {}
