apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/alkuzmanov/go/bin/kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: genesysmysql
  name: genesysmysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: genesysmysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/alkuzmanov/go/bin/kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: genesysmysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: db_example
            - name: MYSQL_PASSWORD
              value: ThePassword
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: springuser
          image: mysql:8.0.21
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 20
            timeoutSeconds: 20
          name: genesysmysql
          ports:
            - containerPort: 3306
          resources: {}
          securityContext:
            capabilities:
              add:
                - SYS_NICE
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/setup.sql
              name: genesysmysql-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: genesysmysql-claim0
          persistentVolumeClaim:
            claimName: genesysmysql-claim0
            readOnly: true
status: {}
