apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: /Users/alkuzmanov/go/bin/kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: genesys
  name: genesys
spec:
  containers:
    - env:
        - name: spring.datasource.driver-class-name
          value: com.mysql.cj.jdbc.Driver
        - name: spring.datasource.url
          value: jdbc:mysql://genesysmysql:3306/db_example?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&serverTimezone=UTC
        - name: spring.jpa.properties.hibernate.dialect
          value: org.hibernate.dialect.MySQL5Dialect
        - name: spring.zipkin.base-url
          value: http://genesyszipkin:9411/
      image: genesys:0.0.1
#      imagePullPolicy: IfNotPresent
      imagePullPolicy: Never
      name: genesys
      ports:
        - containerPort: 8080
      resources: {}
  restartPolicy: OnFailure
status: {}
